# Generated by Django 2.1.5 on 2019-04-22 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField(db_index=True)),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='teleping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, default=None, max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('inet', models.BooleanField(db_index=True)),
                ('vpn', models.BooleanField(db_index=True)),
            ],
        ),
    ]
