# Generated by Django 2.1.5 on 2019-04-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teleofis_state',
            table=None,
        ),
    ]
