# Generated by Django 2.1.5 on 2019-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telelog',
            name='log_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
