# Generated by Django 2.2.2 on 2019-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190610_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telelog',
            name='log_text',
            field=models.TextField(db_index=True, default=None),
        ),
    ]
