# Generated by Django 2.2.2 on 2019-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_telemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='board_temp',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='cpu_temp',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='vin',
            field=models.TextField(db_index=True),
        ),
    ]
