# Generated by Django 2.2.2 on 2019-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190614_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='tele_name',
            field=models.CharField(db_index=True, default=None, max_length=150),
        ),
    ]
