# Generated by Django 2.2.2 on 2019-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_telemetry_tele_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='tele_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
