# Generated by Django 2.2.2 on 2019-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190807_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='tele_name',
            field=models.CharField(db_index=True, default=None, max_length=150),
        ),
    ]
